// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/google/wire"
	"github.com/marcelocampanelli/trello-clone/internal/domain/gateway"
	"github.com/marcelocampanelli/trello-clone/internal/infra/repository"
	"github.com/marcelocampanelli/trello-clone/internal/infra/web/handlers"
	"github.com/marcelocampanelli/trello-clone/internal/usecase/user"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitializeUserHandler(client *mongo.Client) *handlers.UserHandler {
	userRepository := repository.NewUserRepository(client)
	createUserUseCase := user.NewUserCreateUseCase(userRepository)
	updateUserUseCase := user.NewUserUpdateUseCase(userRepository)
	userHandler := handlers.NewUserHandler(createUserUseCase, updateUserUseCase)
	return userHandler
}

// wire.go:

var setUserRepositoryDependency = wire.NewSet(repository.NewUserRepository, wire.Bind(new(gateway.UserGateway), new(*repository.UserRepository)))
