version: '3'
services:
  mongodb:
    image: mongo
    container_name: trello-clonedb
    ports:
      - "27017:27017"
    volumes:
      - .docker:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root