POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "nickname": "jhondoezim",
  "email": "teste@test.com",
  "password": "teste@test",
  "cpf": "76118993092"
}

###

PUT http://localhost:8080/api/v1/users/6542d7c967ec844df4ba98fb
Content-Type: application/json

{
  "first_name": "xDDD",
  "last_name": "=)",
  "nickname": "jhondoezim",
  "password": "123456"
}

###

POST http://localhost:8080/api/v1/users/auth
Content-Type: application/json

{
  "email": "jhon@doeDeeeeee.com",
  "password": "123456"
}