// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	user "github.com/marcelocampanelli/trello-clone/internal/usecase/user"
	mock "github.com/stretchr/testify/mock"
)

// UpdateUserUseCaseInterface is an autogenerated mock type for the UpdateUserUseCaseInterface type
type UpdateUserUseCaseInterface struct {
	mock.Mock
}

// Execute provides a mock function with given fields: input
func (_m *UpdateUserUseCaseInterface) Execute(input *user.UpdateUserInputDTO) (*user.UpdateUserOutputDTO, error) {
	ret := _m.Called(input)

	var r0 *user.UpdateUserOutputDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(*user.UpdateUserInputDTO) (*user.UpdateUserOutputDTO, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(*user.UpdateUserInputDTO) *user.UpdateUserOutputDTO); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UpdateUserOutputDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(*user.UpdateUserInputDTO) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUpdateUserUseCaseInterface creates a new instance of UpdateUserUseCaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateUserUseCaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateUserUseCaseInterface {
	mock := &UpdateUserUseCaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
